services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: all_the_mons_server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_SLUG: "all-the-mons"
      VERSION: "1.0.0-rc.4"
      MEMORY: "20G"
      TZ: "Europe/Brussels"
      DIFFICULTY: "normal"
      CF_API_KEY: ${CF_API_KEY}
      USE_AIKAR_FLAGS: "true"
    volumes:
      - ./data:/data
